def e_digits(n: int) -> str: ...
def phi_digits(n: int) -> str: ...
def pi_digits(n: int) -> str: ...
def sqrt_digits(d: int, n: int) -> str: ...
def is_prime(n: int) -> bool: ...
def first_n_primes(n: int) -> list[int]: ...
